server:
  port: 8081
spring:
  security:
    enabled: false
    user:
      name: admin
      password: admin
    filter:
      order: 10
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yuji
    url: jdbc:postgresql://localhost:5432/online_order_dev
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
#thymeleaf:
#  prefix: classpath:/templates/
#  suffix: .html 
jwt:
  secret: RiJbPZ5TULYdpJ8rm5nSrP5hsmDdpFajpAl5wcTTpj7/NlwCtESvuZH77kGj9Qb03BWuKnlk6/bEDi6s+0N0zg==
  expiration: 3600000
storage:
  path: /Users/vijay/dev/projects/spring-suite/databox/storage