server:
  port: 8081
spring:
  security:
    enabled: false
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yuji
    url: jdbc:postgresql://localhost:5432/online_order_dev
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
#thymeleaf:
#  prefix: classpath:/templates/
#  suffix: .html 
  
